(function(){
const manifest=chrome.runtime.getManifest(),current=manifest.version,productId='junwoo-comprehensive-chat-extension',DB='entry-live-studio-updater-v2',STORE='handles',KEY='extensionSourceDirectory';
const $=id=>document.getElementById(id); let info=null,pkg=null,busy=false;
$('currentVersion').textContent=`v${current}`;
function progress(value,text){$('progressBar').style.width=`${Math.max(0,Math.min(100,value))}%`;if(text)$('status').textContent=text;}
function command(command,payload={}){return chrome.runtime.sendMessage({type:'ENTRY_CHAT_COMMAND',command,payload}).then(r=>{if(!r?.ok)throw new Error(r?.error||'업데이트 명령 실패');return r.result;});}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function loadHandle(){try{const db=await openDb();return await new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}catch(_){return null}}
async function saveHandle(handle){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(handle,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function permission(handle,ask=false){if(!handle)return false;const o={mode:'readwrite'};try{if(await handle.queryPermission(o)==='granted')return true;if(ask&&await handle.requestPermission(o)==='granted')return true}catch(_){}return false;}
async function readJson(handle,name){const fh=await handle.getFileHandle(name);return JSON.parse(await(await fh.getFile()).text());}
async function loadPackage(){progress(10,'업데이트 준비 중…');info=await command('CHECK_UPDATE');if(!info?.available)throw new Error('현재 설치된 버전보다 새로운 업데이트가 없습니다.');$('latestVersion').textContent=`v${info.version}`;const u=new URL(info.downloadUrl);if(u.protocol!=='https:'||u.hostname!=='raw.githubusercontent.com'||!u.pathname.startsWith('/KKomaProgrammer/codingdongari/'))throw new Error('업데이트 주소를 확인할 수 없습니다.');const r=await fetch(`${u.href}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('업데이트 파일을 가져오지 못했습니다.');progress(25,'업데이트 준비 중…');const entries=await EntryChatZipUpdate.readZip(await r.arrayBuffer());const md=new TextDecoder();const me=entries.find(e=>e.path==='manifest.json'),be=entries.find(e=>e.path==='build-info.json');if(!me||!be)throw new Error('업데이트 파일을 확인할 수 없습니다.');const m=JSON.parse(md.decode(me.data)),b=JSON.parse(md.decode(be.data));if(m.name!==manifest.name||Number(m.manifest_version)!==3||String(m.version)!==String(info.version)||String(b.version)!==String(info.version)||!String(b.buildId||'').trim())throw new Error('업데이트 파일 정보가 올바르지 않습니다.');pkg={entries,manifest:m,build:b};progress(35,'업데이트 준비 완료');}
async function dirFor(root,parts){let d=root;for(const p of parts)d=await d.getDirectoryHandle(p,{create:true});return d;}
async function writeEntry(root,e){const parts=e.path.split('/').filter(Boolean),name=parts.pop();if(!name)return;const d=await dirFor(root,parts),fh=await d.getFileHandle(name,{create:true}),w=await fh.createWritable();try{await w.write(e.data)}finally{await w.close()}}
async function validateTarget(handle){const m=await readJson(handle,'manifest.json'),b=await readJson(handle,'build-info.json');if(m.name!==manifest.name||Number(m.manifest_version)!==3)throw new Error('현재 확장 프로그램을 로드한 폴더를 선택하세요.');if(!String(b.buildId||'').trim())throw new Error('선택한 폴더를 확인할 수 없습니다.');return{manifest:m,build:b};}
async function apply(handle){if(busy)return;busy=true;try{await validateTarget(handle);progress(45,'파일 적용 중…');const list=pkg.entries.filter(e=>e.path!=='manifest.json');let n=0;for(const e of list){await writeEntry(handle,e);n++;progress(45+Math.round((n/Math.max(1,list.length))*45),'파일 적용 중…');}await writeEntry(handle,pkg.entries.find(e=>e.path==='manifest.json'));const m=await readJson(handle,'manifest.json'),b=await readJson(handle,'build-info.json');if(String(m.version)!==info.version||String(b.version)!==info.version)throw new Error('업데이트 적용을 확인하지 못했습니다.');progress(100,'업데이트 완료');setTimeout(()=>chrome.runtime.reload(),500);}catch(e){busy=false;progress(35,e?.message||String(e));$('folderButton').hidden=false;}}
async function choose(){try{let h=await window.showDirectoryPicker({mode:'readwrite',id:'entry-live-studio-source'});await validateTarget(h);await saveHandle(h);await apply(h);}catch(e){if(e?.name!=='AbortError')progress(35,e?.message||String(e));$('folderButton').hidden=false;}}
async function startFolderFlow(){const g=$('guide');g.hidden=false;for(let i=3;i>0;i--){$('countdown').textContent=`${i}초 후 폴더 선택을 시작합니다.`;await new Promise(r=>setTimeout(r,1000));}let h=await loadHandle();if(h&&await permission(h,false)){await apply(h);return;}try{await choose();}catch(_){$('folderButton').hidden=false;}}
$('folderButton').addEventListener('click',choose);
(async()=>{try{await loadPackage();await startFolderFlow();}catch(e){progress(0,e?.message||String(e));}})();
})();