from pathlib import Path
import json

root=Path('.')
# updater.js
p=root/'updater.js'; s=p.read_text(encoding='utf-8')
s=s.replace("const $=id=>document.getElementById(id);let info=null,pkg=null,busy=false,savedHandle=null,sourceTabId=null,updateTabId=null,clipboardTimer=null,clipboardInitial='';",
            "const $=id=>document.getElementById(id);let info=null,pkg=null,busy=false,savedHandle=null,sourceTabId=null,updateTabId=null,clipboardInitial='';")
old="""function pickerOptions(){return{mode:'readwrite',id:'entry-live-studio-source'};}\nasync function choose(){try{const h=await window.showDirectoryPicker(pickerOptions());await validateTarget(h);await saveHandle(h);savedHandle=h;await apply(h);}catch(e){if(e?.name!=='AbortError')progress(35,e?.message||String(e));$('folderButton').hidden=false;}}\nfunction plausiblePath(value){const v=String(value||'').trim();if(v.length<3||/^https?:/i.test(v)||/^chrome:/i.test(v))return '';if(/^[A-Za-z]:[\\\\/]/.test(v)||/^\\\\\\\\[^\\\\]+\\\\/.test(v)||/^\\/(Users|home|Volumes|mnt|media)\\//.test(v))return v;return '';}\nasync function readClipboard(){const response=await chrome.runtime.sendMessage({type:'ENTRY_UPDATE_READ_CLIPBOARD'});if(!response?.ok)throw new Error(response?.error||'클립보드 읽기 실패');return String(response.text||'');}\nfunction stopClipboardWatch(){if(clipboardTimer)clearInterval(clipboardTimer);clipboardTimer=null;}\nasync function closeSourceAndReturn(path){stopClipboardWatch();try{if(sourceTabId!=null)await chrome.tabs.remove(sourceTabId);}catch(_){}sourceTabId=null;try{if(updateTabId!=null)await chrome.tabs.update(updateTabId,{active:true});}catch(_){}const g=$('sourceGuide');g.classList.add('done');setTimeout(()=>{g.hidden=true;g.classList.remove('done');},320);$('pathFallback').hidden=true;$('folderButton').hidden=false;progress(35,'로드 위치 경로를 확인했습니다. 폴더 접근 허용을 누르면 Chrome 폴더 선택창이 열립니다. 해당 폴더를 선택하세요.');void path;}\nasync function pollClipboard(){try{const text=await readClipboard(),path=plausiblePath(text);if(path&&text!==clipboardInitial)await closeSourceAndReturn(path);}catch(e){stopClipboardWatch();$('pathFallback').hidden=false;$('folderButton').hidden=false;progress(35,'클립보드 읽기에 실패했습니다. 로드 위치 경로를 아래에 붙여넣은 뒤 폴더 접근 허용을 누르세요.');}}\nasync function openSource(){try{updateTabId=(await chrome.tabs.getCurrent())?.id??null;try{clipboardInitial=await readClipboard();}catch(_){clipboardInitial='';}const sourceUrl=`chrome://extensions/?id=${chrome.runtime.id}`;const tab=await chrome.tabs.create({url:sourceUrl,active:true});sourceTabId=tab?.id??null;stopClipboardWatch();clipboardTimer=setInterval(pollClipboard,700);setTimeout(()=>{if(clipboardTimer){stopClipboardWatch();$('pathFallback').hidden=false;$('folderButton').hidden=false;progress(35,'경로 복사 감지를 기다리고 있습니다. 자동 감지가 되지 않으면 로드 위치 경로를 아래에 붙여넣으세요.');}},90000);}catch(e){$('pathFallback').hidden=false;$('folderButton').hidden=false;progress(35,e?.message||String(e));}}\n"""
new="""function pickerOptions(){return{mode:'readwrite',id:'entry-live-studio-source'};}\nasync function choose(){try{const h=await window.showDirectoryPicker(pickerOptions());await validateTarget(h);await saveHandle(h);savedHandle=h;await apply(h);}catch(e){if(e?.name!=='AbortError')progress(35,e?.message||String(e));$('folderButton').hidden=false;}}\nfunction plausiblePath(value){const v=String(value||'').trim();if(v.length<3||/^https?:/i.test(v)||/^chrome:/i.test(v))return '';if(/^[A-Za-z]:[\\\\/]/.test(v)||/^\\\\\\\\[^\\\\]+\\\\/.test(v)||/^\\/(Users|home|Volumes|mnt|media)\\//.test(v))return v;return '';}\nasync function readClipboard(){const response=await chrome.runtime.sendMessage({type:'ENTRY_UPDATE_READ_CLIPBOARD'});if(!response?.ok)throw new Error(response?.error||'클립보드 읽기 실패');return String(response.text||'');}\nasync function stopClipboardWatch(){try{await chrome.runtime.sendMessage({type:'ENTRY_UPDATE_STOP_CLIPBOARD_WATCH'});}catch(_){}}\nasync function closeSourceAndReturn(path){const detected=plausiblePath(path);if(!detected)return;$('pathInput').value=detected;sourceTabId=null;const g=$('sourceGuide');g.classList.add('done');setTimeout(()=>{g.hidden=true;g.classList.remove('done');},320);$('pathFallback').hidden=true;$('sourceButton').hidden=true;$('folderButton').hidden=false;progress(35,`로드 위치 경로를 자동으로 확인했습니다.\\n${detected}\\n이 기기에서 최초 연결인 경우에만 아래 버튼으로 폴더 접근을 한 번 허용하세요. 이후 업데이트에서는 폴더 선택창을 다시 열지 않습니다.`);}\nasync function openSource(){try{updateTabId=(await chrome.tabs.getCurrent())?.id??null;try{clipboardInitial=await readClipboard();}catch(_){clipboardInitial='';}const sourceUrl=`chrome://extensions/?id=${chrome.runtime.id}`;const tab=await chrome.tabs.create({url:sourceUrl,active:true});sourceTabId=tab?.id??null;const started=await chrome.runtime.sendMessage({type:'ENTRY_UPDATE_START_CLIPBOARD_WATCH',sourceTabId,updateTabId,initialClipboard:clipboardInitial});if(!started?.ok)throw new Error(started?.error||'클립보드 자동 감시를 시작하지 못했습니다.');}catch(e){$('pathFallback').hidden=false;$('folderButton').hidden=false;progress(35,e?.message||String(e));}}\n"""
assert old in s
s=s.replace(old,new,1)
old2="""$('sourceButton').addEventListener('click',openSource);\n$('folderButton').addEventListener('click',choose);\n$('pathInput').addEventListener('input',()=>{if(plausiblePath($('pathInput').value))$('folderButton').hidden=false;});\nwindow.addEventListener('pagehide',stopClipboardWatch);\n"""
new2="""$('sourceButton').addEventListener('click',openSource);\n$('folderButton').addEventListener('click',choose);\n$('pathInput').addEventListener('input',()=>{const path=plausiblePath($('pathInput').value);if(path){$('folderButton').hidden=false;chrome.runtime.sendMessage({type:'ENTRY_UPDATE_MANUAL_PATH_READY',path,sourceTabId,updateTabId}).catch(()=>{});}});\nchrome.runtime.onMessage.addListener((message)=>{if(message?.type==='ENTRY_UPDATE_PATH_DETECTED'&&(!updateTabId||message.updateTabId===updateTabId))closeSourceAndReturn(message.path);if(message?.type==='ENTRY_UPDATE_CLIPBOARD_WATCH_ERROR'&&(!updateTabId||message.updateTabId===updateTabId)){$('pathFallback').hidden=false;$('folderButton').hidden=false;progress(35,'클립보드 자동 읽기가 제한되었습니다. 로드 위치 경로를 아래에 붙여넣으세요. 이전에 폴더를 연결한 적이 있다면 이 단계 없이 저장된 폴더를 재사용합니다.');}});\nwindow.addEventListener('pagehide',()=>{stopClipboardWatch();});\n"""
assert old2 in s
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')

# offscreen clipboard.js
(root/'offscreen/clipboard.js').write_text("""let watchTimer=null;\nlet watchLast='';\nlet watchFailures=0;\nfunction stopWatch(){if(watchTimer)clearInterval(watchTimer);watchTimer=null;watchFailures=0;}\nfunction plausiblePath(value){const v=String(value||'').trim();if(v.length<3||/^https?:/i.test(v)||/^chrome:/i.test(v))return '';if(/^[A-Za-z]:[\\\\/]/.test(v)||/^\\\\\\\\[^\\\\]+\\\\/.test(v)||/^\\/(Users|home|Volumes|mnt|media)\\//.test(v))return v;return '';}\nasync function readClipboard(){return String(await navigator.clipboard.readText()||'');}\nasync function sampleClipboard(){try{const text=await readClipboard();watchFailures=0;if(text!==watchLast){watchLast=text;const path=plausiblePath(text);if(path){stopWatch();chrome.runtime.sendMessage({type:'ENTRY_OFFSCREEN_CLIPBOARD_CHANGED',target:'background',text:path}).catch(()=>{});}}}catch(error){watchFailures++;if(watchFailures===8){chrome.runtime.sendMessage({type:'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_ERROR',target:'background',error:error?.message||String(error)}).catch(()=>{});}}}\nfunction startWatch(initial){stopWatch();watchLast=String(initial||'');watchFailures=0;watchTimer=setInterval(sampleClipboard,400);sampleClipboard();}\nchrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{\n  if(message?.target!=='offscreen')return;\n  if(message?.type==='ENTRY_OFFSCREEN_CLIPBOARD_READ'){readClipboard().then(text=>sendResponse({ok:true,text})).catch(error=>sendResponse({ok:false,error:error?.message||String(error)}));return true;}\n  if(message?.type==='ENTRY_OFFSCREEN_CLIPBOARD_WATCH_START'){startWatch(message.initialClipboard);sendResponse({ok:true});return;}\n  if(message?.type==='ENTRY_OFFSCREEN_CLIPBOARD_WATCH_STOP'){stopWatch();sendResponse({ok:true});return;}\n});\n""",encoding='utf-8')

# background.js
p=root/'background.js'; s=p.read_text(encoding='utf-8')
anchor="""async function _0x0404() {\n    await _0x0401();\n    const _0x0405 = await chrome.runtime.sendMessage({ type: 'ENTRY_OFFSCREEN_CLIPBOARD_READ', target: 'offscreen' });\n    if (!_0x0405?.ok)\n        throw new Error(_0x0405?.error || '클립보드 읽기에 실패했습니다.');\n    return String(_0x0405.text || '');\n}\n"""
insert=anchor+"""let _0x0408 = null;\nfunction _0x0409(_0x040a) {\n    const _0x040b = String(_0x040a || '').trim();\n    if (_0x040b.length < 3 || /^https?:/i.test(_0x040b) || /^chrome:/i.test(_0x040b))\n        return '';\n    if (/^[A-Za-z]:[\\\\/]/.test(_0x040b) || /^\\\\\\\\[^\\\\]+\\\\/.test(_0x040b) || /^\\/(Users|home|Volumes|mnt|media)\\//.test(_0x040b))\n        return _0x040b;\n    return '';\n}\nasync function _0x040a(_0x040c) {\n    try {\n        await _0x0401();\n        await chrome.runtime.sendMessage({ type: 'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_STOP', target: 'offscreen' }).catch(() => { });\n        const _0x040d = Number(_0x040c?.sourceTabId);\n        const _0x040e = Number(_0x040c?.updateTabId);\n        _0x0408 = { sourceTabId: Number.isFinite(_0x040d) ? _0x040d : null, updateTabId: Number.isFinite(_0x040e) ? _0x040e : null };\n        const _0x040f = await chrome.runtime.sendMessage({ type: 'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_START', target: 'offscreen', initialClipboard: String(_0x040c?.initialClipboard || '') });\n        if (!_0x040f?.ok)\n            throw new Error(_0x040f?.error || '클립보드 감시 시작 실패');\n        return { ok: true };\n    }\n    catch (_0x0410) {\n        _0x0408 = null;\n        return { ok: false, error: _0x0410?.message || String(_0x0410) };\n    }\n}\nasync function _0x0411() {\n    await chrome.runtime.sendMessage({ type: 'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_STOP', target: 'offscreen' }).catch(() => { });\n    _0x0408 = null;\n}\nasync function _0x0412(_0x0413) {\n    const _0x0414 = _0x0409(_0x0413);\n    if (!_0x0414 || !_0x0408)\n        return;\n    const _0x0415 = _0x0408;\n    _0x0408 = null;\n    await chrome.runtime.sendMessage({ type: 'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_STOP', target: 'offscreen' }).catch(() => { });\n    if (_0x0415.sourceTabId != null)\n        await chrome.tabs.remove(_0x0415.sourceTabId).catch(() => { });\n    if (_0x0415.updateTabId != null)\n        await chrome.tabs.update(_0x0415.updateTabId, { active: true }).catch(() => { });\n    await chrome.runtime.sendMessage({ type: 'ENTRY_UPDATE_PATH_DETECTED', updateTabId: _0x0415.updateTabId, path: _0x0414 }).catch(() => { });\n}\n"""
assert anchor in s
s=s.replace(anchor,insert,1)
needle="""chrome.runtime.onMessage.addListener((_0x01b9, _0x01ba, _0x01bb) => {\n    if (_0x01b9?.type === 'ENTRY_UPDATE_READ_CLIPBOARD') {\n"""
replacement="""chrome.runtime.onMessage.addListener((_0x01b9, _0x01ba, _0x01bb) => {\n    if (_0x01b9?.type === 'ENTRY_UPDATE_START_CLIPBOARD_WATCH') {\n        const _0x0416 = { ..._0x01b9, updateTabId: _0x01ba?.tab?.id ?? _0x01b9?.updateTabId };\n        _0x040a(_0x0416).then(_0x01bb);\n        return true;\n    }\n    if (_0x01b9?.type === 'ENTRY_UPDATE_STOP_CLIPBOARD_WATCH') {\n        _0x0411().then(() => _0x01bb({ ok: true })).catch((_0x0417) => _0x01bb({ ok: false, error: _0x0417?.message || String(_0x0417) }));\n        return true;\n    }\n    if (_0x01b9?.type === 'ENTRY_OFFSCREEN_CLIPBOARD_CHANGED' && _0x01b9?.target === 'background') {\n        _0x0412(_0x01b9.text);\n        return;\n    }\n    if (_0x01b9?.type === 'ENTRY_OFFSCREEN_CLIPBOARD_WATCH_ERROR' && _0x01b9?.target === 'background') {\n        if (_0x0408)\n            chrome.runtime.sendMessage({ type: 'ENTRY_UPDATE_CLIPBOARD_WATCH_ERROR', updateTabId: _0x0408.updateTabId, error: _0x01b9.error || '클립보드 읽기 실패' }).catch(() => { });\n        return;\n    }\n    if (_0x01b9?.type === 'ENTRY_UPDATE_MANUAL_PATH_READY') {\n        const _0x0418 = _0x0409(_0x01b9.path);\n        if (_0x0418 && _0x0408) {\n            const _0x0419 = _0x0408;\n            if (_0x0419.sourceTabId != null)\n                chrome.tabs.remove(_0x0419.sourceTabId).catch(() => { });\n            if (_0x0419.updateTabId != null)\n                chrome.tabs.update(_0x0419.updateTabId, { active: true }).catch(() => { });\n        }\n        return;\n    }\n    if (_0x01b9?.type === 'ENTRY_UPDATE_READ_CLIPBOARD') {\n"""
assert needle in s
s=s.replace(needle,replacement,1)
anchor2="""chrome.action.onClicked.addListener((_0x01be) => {\n"""
assert anchor2 in s
s=s.replace(anchor2,"""chrome.tabs.onRemoved.addListener((_0x041a) => {\n    if (_0x0408?.sourceTabId === _0x041a)\n        _0x0411().catch(() => { });\n});\n"""+anchor2,1)
p.write_text(s,encoding='utf-8')

# updater.html
p=root/'updater.html'; s=p.read_text(encoding='utf-8')
s=s.replace('경로 복사를 감지하면 출처 페이지를 닫고 이 업데이트 페이지로 자동 복귀합니다.','경로 복사를 offscreen에서 감지하므로 이 페이지가 백그라운드여도 동작합니다. 감지 즉시 출처 페이지를 닫고 업데이트 페이지로 자동 복귀합니다.')
s=s.replace('클립보드 읽기에 실패했습니다. 로드 위치 경로를 붙여넣으세요.','자동 감지에 실패한 경우에만 로드 위치 경로를 붙여넣으세요.')
s=s.replace('>폴더 접근 허용</button>','>폴더 접근 연결 (최초 1회)</button>')
p.write_text(s,encoding='utf-8')

# changelog
(root/'CHANGELOG-v2.2.9.md').write_text('''# v2.2.9\n\n- 업데이트 출처 경로 감지를 updater 탭 타이머에서 offscreen 지속 감시 방식으로 변경했습니다.\n- 로드 위치 경로 복사 감지 시 `chrome://extensions` 탭을 자동으로 닫고 updater 탭으로 복귀합니다.\n- 감지한 경로를 updater 입력 상태에 실제 반영합니다.\n- 이미 저장된 FileSystemDirectoryHandle이 있으면 폴더 선택창 없이 재사용하며, 권한 만료 시 기존 핸들의 권한만 다시 요청합니다.\n- 최초 연결에만 `showDirectoryPicker()`를 사용하며 동일 picker id로 Chrome의 최근 위치 기억을 재사용합니다.\n''',encoding='utf-8')

# version metadata
m=json.loads((root/'manifest.json').read_text(encoding='utf-8')); m['version']='2.2.9'; (root/'manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
b=json.loads((root/'build-info.json').read_text(encoding='utf-8')); b['version']='2.2.9'; b['buildId']='eb21d128-d8d2-4578-9eda-1da69fb4e87e'; b['createdAt']='2026-09-16T12:45:12.925994Z';
if 'CHANGELOG-v2.2.9.md' not in b['managedFiles']: b['managedFiles'].append('CHANGELOG-v2.2.9.md')
(root/'build-info.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
